### ISSUE TITLE
Spacing mixin troubles and potential fixes

### ISSUE THREAD

**Issue by Jonic** [RaspberryPiFoundation/sauce-design-system#41]
See #40 for some reference.

Currently the `margin` and `padding` mixins output three breakpoints. This was in order to have a system that allowed for different scaling at different screen sizes. However its implementation was a little short sighted. Consider:

```sass
.selector {
  @include padding.inline('bee');
}
```

...outputs this CSS:

```css
.selector {
  padding-left: 1.6rem;
  padding-right: 1.6rem;
  padding-inline: 1.6rem;
}

@media screen and (min-width: 800px) {
  .selector {
    padding-left: 2rem;
    padding-right: 2rem;
    padding-inline: 2rem;
  }
}

@media screen and (min-width: 1200px) {
  .selector {
    padding-left: 2.4rem;
    padding-right: 2.4rem;
    padding-inline: 2.4rem;
  }
}
```

But this doesn't cater for situations where you need to specify differing paddings at breakpoints other than 800 and 1200 pixels `min-width`. This has led to a forced implementation error, where developers have no choice but to do this kind of thing:

```sass
.selector {
  // [1] base padding
  @include padding.inline('bee');

  // [2] min-width 700
  @include device.min-width(700px) {
    @include padding.inline('eagle');
  }

  // [3] min-width 1000
  @include device.min-width(1000px) {
    @include padding.inline('grizzly');
  }
}
```

The outcome of which is this (outputting a complete example to illustrate just how sub-optimal this situation is):

```css
/* [1] base padding */
.selector {
  padding-left: 1.6rem;
  padding-right: 1.6rem;
  padding-inline: 1.6rem;
}

@media screen and (min-width: 800px) {
  .selector {
    padding-left: 2rem;
    padding-right: 2rem;
    padding-inline: 2rem;
  }
}

@media screen and (min-width: 1200px) {
  .selector {
    padding-left: 2.4rem;
    padding-right: 2.4rem;
    padding-inline: 2.4rem;
  }
}

/* [2] min-width 700 */
@media screen and (min-width: 700px) {
  .selector {
    padding-left: 4rem;
    padding-right: 4rem;
    padding-inline: 4rem;
  }
}

@media screen and (min-width: 700px) and (min-width: 800px) {
  .selector {
    padding-left: 5rem;
    padding-right: 5rem;
    padding-inline: 5rem;
  }
}

@media screen and (min-width: 700px) and (min-width: 1200px) {
  .selector {
    padding-left: 6rem;
    padding-right: 6rem;
    padding-inline: 6rem;
  }
}

/* [3] min-width 1000 */
@media screen and (min-width: 1000px) {
  .selector {
    padding-left: 5.6rem;
    padding-right: 5.6rem;
    padding-inline: 5.6rem;
  }
}

@media screen and (min-width: 1000px) and (min-width: 800px) {
  .selector {
    padding-left: 7rem;
    padding-right: 7rem;
    padding-inline: 7rem;
  }
}

@media screen and (min-width: 1000px) and (min-width: 1200px) {
  .selector {
    padding-left: 8.4rem;
    padding-right: 8.4rem;
    padding-inline: 8.4rem;
  }
}
```

So you can see, this needs some work. The biggest problem is the framework's insistence that there are no **set** breakpoints, while at the same time using very rigidly set breakpoints in itself. This is incredibly dangerous because—while this **is** documented—it is not _obvious_ that the mixins output that CSS.

This is entirely on me. It was necessary at the time to run with this system in order to get Sauce up and running, but I should have considered the longer term implications of this when we got to the application-level. Furthermore I should have made the output of the mixins super obvious. When dev docs arrive, I'll make sure that each mixin has a `sass`/`css` comparison.

The good news is that this is easier to fix than we might think. CSS `clamp()` will allow us to specify values that scale with the browser, without exceeding a minimum or maximum size. We should be able to convert these mixins to start using `clamp()` fairly easily, so long as we consider how to do so without breaking any applications where they are currently implemented.
